## Modeling the agent
1. Feature selection: remove the columns I will not use (for example, the indexing, lat, longitude, and name of the station)
2. Train the models with resampling
3. .....

### Libraries and tools to ues

### Preparation on google colab

!pip install -U ipython

In [ ]:
"""
%load_ext autoreload
%autoreload 2

#Clone the repository
import os
if not os.path.exists("your-project"):
    !git clone https://github.com/ras112git/predictive_modeling_and_mobility_forecasting.git
else:
    print("Repo already cloned.")


%cd predictive_modeling_and_mobility_forecasting

# Install dependencies
!pip install -r requirements.txt

import sys
sys.path.append(os.getcwd())
"""

### Preparation of the venvironment (as on the other notebooks)

In [1]:
%load_ext autoreload
%autoreload 2

import sys, os
from pathlib import Path

# Make src/ importable: add the project root (parent of notebooks/) to sys.path
project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Run from the project root so relative paths like "data/raw/..." resolve
os.chdir(project_root)
print(f"Working dir: {os.getcwd()}")

Working dir: c:\Users\rcsrc\Documents\GitHub\predictive_modeling_and_mobility_forecasting

### Automatically clean the data

In [2]:
from src.model import *

import pandas as pd

# Start by importing the data
train_path = Path('data/raw/dataset_train.csv')
df_train = pd.read_csv(train_path)

In [3]:
# I will clean it heare, as if I cleaned it and saved it as csv, then the categories will be missed

from src.data_cleaning import clean_data

df_train = clean_data(dataset= df_train, 
                      is_train = True, 
                      categorize_station = True) # If I put false here, it splits the station data in bolean

df_train

,id,datetime,station_number,name,lat,lng,bikes,hour,minute,dayofweek,...,hour_cos,is_holiday,avg_bikes_per_station,temperature_2m,apparent_temperature,precipitation,snowfall,wind_speed_10m,cloud_cover,relative_humidity_2m
0,2024-09-03 17:30:00_32000,2024-09-03 17:30:00,32000,Julius-Raab-Platz,48.211544,16.382374,25,17,30,1,...,-0.258819,0,9.258033,28.8,27.7,0.0,0.0,8.4,6,32
1,2024-09-03 17:30:00_32001,2024-09-03 17:30:00,32001,Hoher Markt,48.210666,16.372983,14,17,30,1,...,-0.258819,0,16.898142,28.8,27.7,0.0,0.0,8.4,6,32
2,2024-09-03 17:30:00_32002,2024-09-03 17:30:00,32002,Oper,48.202683,16.369702,9,17,30,1,...,-0.258819,0,14.598361,28.8,27.7,0.0,0.0,8.4,6,32
3,2024-09-03 17:30:00_32003,2024-09-03 17:30:00,32003,Volksgarten,48.206516,16.360400,3,17,30,1,...,-0.258819,0,7.415082,28.8,27.7,0.0,0.0,8.4,6,32
4,2024-09-03 17:30:00_32004,2024-09-03 17:30:00,32004,Taborstraße U2,48.219522,16.382218,5,17,30,1,...,-0.258819,0,12.433880,28.8,27.7,0.0,0.0,8.4,6,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150245,2025-03-13 08:00:00_32275,2025-03-13 08:00:00,32275,eLastenräder - Am langen Felde,48.250224,16.450650,0,8,0,3,...,-0.500000,0,0.675519,10.1,7.2,0.5,0.0,16.4,100,88
2150246,2025-03-13 08:00:00_32277,2025-03-13 08:00:00,32277,eLastenräder - Bruno-Marek-Allee 6,48.227914,16.391516,6,8,0,3,...,-0.500000,0,3.513661,10.1,7.2,0.5,0.0,16.4,100,88
2150247,2025-03-13 08:00:00_32278,2025-03-13 08:00:00,32278,eLastenräder - Am Tabor 23,48.224598,16.392090,3,8,0,3,...,-0.500000,0,2.462186,10.1,7.2,0.5,0.0,16.4,100,88
2150248,2025-03-13 08:00:00_32280,2025-03-13 08:00:00,32280,ALF Mobility-Point,48.251355,16.452810,5,8,0,3,...,-0.500000,0,4.515519,10.1,7.2,0.5,0.0,16.4,100,88
2150249,2025-03-13 08:00:00_32283,2025-03-13 08:00:00,32283,eLastenräder- Modecenterstraße / The Marks,48.184929,16.413964,2,8,0,3,...,-0.500000,0,0.886557,10.1,7.2,0.5,0.0,16.4,100,88

### Feature selection

In [4]:
# Split the features

TARGET = "bikes"

x_train, y_train = data_split(df_train,target=TARGET)
#print(X_train)

In [5]:
#Make sure that the data is ordered by datetime
assert x_train['datetime'].is_monotonic_increasing

DROP_COLS = ["id", "datetime", "name", "lat", "lng"] #

x_train = prepare_features(X = x_train, drop_cols=DROP_COLS)

In [6]:
# featurce_performance = feature_selection_report(x_train,y_train)

# print("features:", featurce_performance)
# print("train data shape:", x_train.shape)

In [7]:
x_train

,station_number,hour,minute,dayofweek,month,is_weekend,hour_sin,hour_cos,is_holiday,avg_bikes_per_station,temperature_2m,apparent_temperature,precipitation,snowfall,wind_speed_10m,cloud_cover,relative_humidity_2m
0,32000,17,30,1,9,0,-0.965926,-0.258819,0,9.258033,28.8,27.7,0.0,0.0,8.4,6,32
1,32001,17,30,1,9,0,-0.965926,-0.258819,0,16.898142,28.8,27.7,0.0,0.0,8.4,6,32
2,32002,17,30,1,9,0,-0.965926,-0.258819,0,14.598361,28.8,27.7,0.0,0.0,8.4,6,32
3,32003,17,30,1,9,0,-0.965926,-0.258819,0,7.415082,28.8,27.7,0.0,0.0,8.4,6,32
4,32004,17,30,1,9,0,-0.965926,-0.258819,0,12.433880,28.8,27.7,0.0,0.0,8.4,6,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150245,32275,8,0,3,3,0,0.866025,-0.500000,0,0.675519,10.1,7.2,0.5,0.0,16.4,100,88
2150246,32277,8,0,3,3,0,0.866025,-0.500000,0,3.513661,10.1,7.2,0.5,0.0,16.4,100,88
2150247,32278,8,0,3,3,0,0.866025,-0.500000,0,2.462186,10.1,7.2,0.5,0.0,16.4,100,88
2150248,32280,8,0,3,3,0,0.866025,-0.500000,0,4.515519,10.1,7.2,0.5,0.0,16.4,100,88
2150249,32283,8,0,3,3,0,0.866025,-0.500000,0,0.886557,10.1,7.2,0.5,0.0,16.4,100,88

### Benchmarking different methods

In [8]:
#I first need to create all the models that I will asses
model_grid = get_model_grid(Feature_df=x_train)

In [9]:
#Then i train them with the default folds
benchmark_results = benchmark_models(X=x_train,y=y_train,models=model_grid,sample_size=200_000)

c:\Users\rcsrc\Documents\GitHub\predictive_modeling_and_mobility_forecasting\.venv\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 2 is smaller than n_iter=8. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\rcsrc\Documents\GitHub\predictive_modeling_and_mobility_forecasting\.venv\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 2 is smaller than n_iter=8. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\rcsrc\Documents\GitHub\predictive_modeling_and_mobility_forecasting\.venv\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 2 is smaller than n_iter=8. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

  Featureless fold 1/3: RMSE=9.886  MAE=7.731 RMSLE=1.010
  Featureless fold 2/3: RMSE=8.842  MAE=6.963 RMSLE=0.890
  Featureless fold 3/3: RMSE=9.113  MAE=7.227 RMSLE=0.915
  decision_tree fold 1/3: RMSE=7.373  MAE=5.507 RMSLE=0.738
  decision_tree fold 2/3: RMSE=7.076  MAE=5.446 RMSLE=0.777
  decision_tree fold 3/3: RMSE=6.582  MAE=4.909 RMSLE=0.695
  random_forest fold 1/3: RMSE=6.991  MAE=5.251 RMSLE=0.696
  random_forest fold 2/3: RMSE=6.156  MAE=4.791 RMSLE=0.680

KeyboardInterrupt:

In [ ]:
print(benchmark_results)

In [ ]:
#Finally we print to see the higher performing
from src.model import plot_benchmark

fig, ax = plot_benchmark(benchmark_results)

### Seeing those results, we now select one of the models and train it
This time with more hyperparameters, during a longer period of time, and with a more overall complex resampling strategy.

In [10]:
# Remember to pass a model that handles categorical data, if there will be categorical data in pd version
model_name = "lightgbm"


#model_name = benchmark_results.iloc[0]['model']

best_params, search = train_hyperparameters(
    X=x_train, y=y_train, model_name=model_name, n_iter=40, log_target=True, sample_size=100_000
)

#sample_size to be specified, n_iter

[train_hyperparameters] model=lightgbm  log_target=True  rows=100,000  features=17  n_iter=40  cv_splits=3  total_fits=120  scoring=rmsle
[train_hyperparameters] param grid keys: ['regressor__colsample_bytree', 'regressor__learning_rate', 'regressor__max_depth', 'regressor__min_child_samples', 'regressor__n_estimators', 'regressor__num_leaves', 'regressor__reg_alpha', 'regressor__reg_lambda', 'regressor__subsample']

[  1/40] mean_rmsle=0.6597  std=0.0618  folds=['0.617', '0.747', '0.615']  time=35.0s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 511, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 5, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 0.6}
[  2/40] mean_rmsle=0.6627  std=0.0664  folds=['0.619', '0.757', '0.613']  time=23.3s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 511, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 5, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.8}
[  3/40] mean_rmsle=0.6625  std=0.0615  folds=['0.612', '0.749', '0.626']  time=58.6s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 511, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 5, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 0.6}
[  4/40] mean_rmsle=0.6411  std=0.0564  folds=['0.597', '0.721', '0.606']  time=38.8s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 511, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 100, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}
[  5/40] mean_rmsle=0.6413  std=0.0577  folds=['0.599', '0.723', '0.602']  time=3.9s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 255, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 5, 'regressor__max_depth': 6, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 0.6}
[  6/40] mean_rmsle=0.6614  std=0.0603  folds=['0.614', '0.746', '0.624']  time=6.6s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 10, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 0.8}
[  7/40] mean_rmsle=0.6584  std=0.0610  folds=['0.610', '0.744', '0.621']  time=45.1s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 255, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 10, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 1.0}
[  8/40] mean_rmsle=0.6549  std=0.0632  folds=['0.615', '0.744', '0.606']  time=16.6s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 63, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 50, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 0.6}
[  9/40] mean_rmsle=0.6625  std=0.0577  folds=['0.621', '0.744', '0.622']  time=44.0s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 255, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 100, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 0.9}
[ 10/40] mean_rmsle=0.6438  std=0.0563  folds=['0.601', '0.723', '0.607']  time=3.8s  params={'regressor__subsample': 1.0, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 50, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 1.0}
[ 11/40] mean_rmsle=0.6672  std=0.0675  folds=['0.618', '0.763', '0.621']  time=8.6s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 511, 'regressor__n_estimators': 400, 'regressor__min_child_samples': 10, 'regressor__max_depth': 6, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.9}
[ 12/40] mean_rmsle=0.6555  std=0.0609  folds=['0.614', '0.742', '0.611']  time=9.5s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 20, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.6}
[ 13/40] mean_rmsle=0.6656  std=0.0574  folds=['0.622', '0.747', '0.629']  time=29.5s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 255, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 100, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 1.0}
[ 14/40] mean_rmsle=0.6347  std=0.0499  folds=['0.587', '0.704', '0.613']  time=6.1s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}
[ 15/40] mean_rmsle=0.6389  std=0.0578  folds=['0.595', '0.721', '0.601']  time=30.5s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 255, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 5, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.6}
[ 16/40] mean_rmsle=0.6553  std=0.0637  folds=['0.612', '0.745', '0.608']  time=23.6s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.7}
[ 17/40] mean_rmsle=0.6682  std=0.0682  folds=['0.616', '0.765', '0.624']  time=15.3s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 127, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 10, 'regressor__max_depth': 6, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 1.0}
[ 18/40] mean_rmsle=0.6389  std=0.0590  folds=['0.597', '0.722', '0.598']  time=13.8s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 50, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.9}
[ 19/40] mean_rmsle=0.6544  std=0.0644  folds=['0.610', '0.746', '0.607']  time=18.0s  params={'regressor__subsample': 1.0, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 255, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 50, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.7}
[ 20/40] mean_rmsle=0.6630  std=0.0618  folds=['0.626', '0.750', '0.613']  time=14.2s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 50, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 1.0}
[ 21/40] mean_rmsle=0.6464  std=0.0588  folds=['0.606', '0.730', '0.604']  time=24.2s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 63, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 5, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.9}
[ 22/40] mean_rmsle=0.6565  std=0.0638  folds=['0.613', '0.747', '0.610']  time=15.9s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 63, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 10, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 0.6}
[ 23/40] mean_rmsle=0.6602  std=0.0596  folds=['0.615', '0.744', '0.622']  time=19.1s  params={'regressor__subsample': 1.0, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 511, 'regressor__n_estimators': 400, 'regressor__min_child_samples': 20, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.6}
[ 24/40] mean_rmsle=0.6664  std=0.0647  folds=['0.621', '0.758', '0.621']  time=22.9s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 100, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 0.9}
[ 25/40] mean_rmsle=0.6631  std=0.0573  folds=['0.617', '0.744', '0.629']  time=6.6s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 50, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 0.7}
[ 26/40] mean_rmsle=0.6746  std=0.0656  folds=['0.630', '0.767', '0.626']  time=11.2s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 255, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 50, 'regressor__max_depth': 6, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.9}
[ 27/40] mean_rmsle=0.6593  std=0.0554  folds=['0.620', '0.738', '0.620']  time=36.1s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 511, 'regressor__n_estimators': 400, 'regressor__min_child_samples': 50, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.6}
[ 28/40] mean_rmsle=0.6566  std=0.0645  folds=['0.613', '0.748', '0.609']  time=3.6s  params={'regressor__subsample': 1.0, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 1.0}
[ 29/40] mean_rmsle=0.6551  std=0.0638  folds=['0.611', '0.745', '0.609']  time=8.5s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 20, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 0.8}
[ 30/40] mean_rmsle=0.6426  std=0.0582  folds=['0.597', '0.725', '0.606']  time=18.3s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 50, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.8}
[ 31/40] mean_rmsle=0.6467  std=0.0557  folds=['0.609', '0.726', '0.606']  time=5.3s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 63, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.05, 'regressor__colsample_bytree': 0.8}
[ 32/40] mean_rmsle=0.6550  std=0.0655  folds=['0.611', '0.748', '0.606']  time=17.1s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 63, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 20, 'regressor__max_depth': 6, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.6}
[ 33/40] mean_rmsle=0.6639  std=0.0639  folds=['0.619', '0.754', '0.618']  time=9.5s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 63, 'regressor__n_estimators': 400, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.1, 'regressor__colsample_bytree': 1.0}
[ 34/40] mean_rmsle=0.6502  std=0.0576  folds=['0.608', '0.732', '0.611']  time=18.9s  params={'regressor__subsample': 1.0, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 255, 'regressor__n_estimators': 400, 'regressor__min_child_samples': 20, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.6}
[ 35/40] mean_rmsle=0.6699  std=0.0699  folds=['0.617', '0.769', '0.624']  time=12.0s  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 31, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 10, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.15, 'regressor__colsample_bytree': 0.9}
[ 36/40] mean_rmsle=0.6541  std=0.0589  folds=['0.610', '0.737', '0.615']  time=20.2s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 0, 'regressor__reg_alpha': 0.1, 'regressor__num_leaves': 63, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 5, 'regressor__max_depth': 12, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.8}
[ 37/40] mean_rmsle=0.6480  std=0.0583  folds=['0.609', '0.730', '0.604']  time=10.7s  params={'regressor__subsample': 0.6, 'regressor__reg_lambda': 1.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 600, 'regressor__min_child_samples': 100, 'regressor__max_depth': 6, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.7}
[ 38/40] mean_rmsle=0.6541  std=0.0614  folds=['0.611', '0.741', '0.610']  time=35.6s  params={'regressor__subsample': 1.0, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 1.0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 1000, 'regressor__min_child_samples': 20, 'regressor__max_depth': -1, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.8}
[ 39/40] mean_rmsle=0.6441  std=0.0600  folds=['0.599', '0.729', '0.605']  time=27.6s  params={'regressor__subsample': 0.9, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 511, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 10, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}
[ 40/40] mean_rmsle=0.6477  std=0.0627  folds=['0.600', '0.736', '0.606']  time=11.1s  params={'regressor__subsample': 0.7, 'regressor__reg_lambda': 10.0, 'regressor__reg_alpha': 0.01, 'regressor__num_leaves': 31, 'regressor__n_estimators': 800, 'regressor__min_child_samples': 5, 'regressor__max_depth': 10, 'regressor__learning_rate': 0.03, 'regressor__colsample_bytree': 0.7}

[train_hyperparameters] search done in 779.4s. Best mean_rmsle=0.6347  params={'regressor__subsample': 0.8, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}

In [11]:
print(best_params)

{'regressor__subsample': 0.8, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}

In [12]:
# best_params = {'regressor__subsample': 0.8, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}

model = train_final_model(
    X=x_train, y=y_train, model_name=model_name,
    best_params=best_params, log_target=True,   # optionally sample_size=...
)

[train_final_model] refitting lightgbm on rows=2,150,250, features=17, log_target=True...
[train_final_model] params: {'regressor__subsample': 0.8, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}

In [13]:
print(model)
print(search)

TransformedTargetRegressor(check_inverse=False, func=<ufunc 'log1p'>,
                           inverse_func=<ufunc 'expm1'>,
                           regressor=LGBMRegressor(colsample_bytree=0.7,
                                                   learning_rate=0.01,
                                                   max_depth=8,
                                                   min_child_samples=100,
                                                   n_estimators=200, n_jobs=-2,
                                                   num_leaves=127,
                                                   objective='regression',
                                                   random_state=42, reg_alpha=0,
                                                   reg_lambda=0.1,
                                                   subsample=0.8, verbose=-1))
namespace(best_params_={'regressor__subsample': 0.8, 'regressor__reg_lambda': 0.1, 'regressor__reg_alpha': 0, 'regressor__num_leaves': 127, 'regressor__n_estimators': 200, 'regressor__min_child_samples': 100, 'regressor__max_depth': 8, 'regressor__learning_rate': 0.01, 'regressor__colsample_bytree': 0.7}, best_score_=np.float64(-0.6347006353271697), results_df=    iter  mean_rmsle  std_rmsle  \
0     14    0.634701   0.049851
1     15    0.638910   0.057801
2     18    0.638930   0.058979
3      4    0.641088   0.056423
4      5    0.641266   0.057688
5     30    0.642638   0.058231
6     10    0.643797   0.056266
7     39    0.644105   0.060009
8     21    0.646446   0.058763
9     31    0.646742   0.055720
10    40    0.647693   0.062700
11    37    0.647951   0.058288
12    34    0.650170   0.057595
13    36    0.654068   0.058929
14    38    0.654145   0.061426
15    19    0.654407   0.064437
16     8    0.654873   0.063216
17    32    0.654972   0.065537
18    29    0.655134   0.063814
19    16    0.655251   0.063745
20    12    0.655522   0.060929
21    22    0.656519   0.063785
22    28    0.656554   0.064463
23     7    0.658396   0.061002
24    27    0.659258   0.055372
25     1    0.659686   0.061822
26    23    0.660227   0.059581
27     6    0.661353   0.060307
28     9    0.662462   0.057691
29     3    0.662486   0.061500
30     2    0.662739   0.066396
31    20    0.662985   0.061836
32    25    0.663138   0.057269
33    33    0.663915   0.063899
34    13    0.665638   0.057446
35    24    0.666385   0.064655
36    11    0.667182   0.067516
37    17    0.668233   0.068201
38    35    0.669859   0.069939
39    26    0.674615   0.065600

                                               params  \
0   {'regressor__subsample': 0.8, 'regressor__reg_...
1   {'regressor__subsample': 0.6, 'regressor__reg_...
2   {'regressor__subsample': 0.7, 'regressor__reg_...
3   {'regressor__subsample': 0.9, 'regressor__reg_...
4   {'regressor__subsample': 0.9, 'regressor__reg_...
5   {'regressor__subsample': 0.6, 'regressor__reg_...
6   {'regressor__subsample': 1.0, 'regressor__reg_...
7   {'regressor__subsample': 0.9, 'regressor__reg_...
8   {'regressor__subsample': 0.9, 'regressor__reg_...
9   {'regressor__subsample': 0.9, 'regressor__reg_...
10  {'regressor__subsample': 0.7, 'regressor__reg_...
11  {'regressor__subsample': 0.6, 'regressor__reg_...
12  {'regressor__subsample': 1.0, 'regressor__reg_...
13  {'regressor__subsample': 0.9, 'regressor__reg_...
14  {'regressor__subsample': 1.0, 'regressor__reg_...
15  {'regressor__subsample': 1.0, 'regressor__reg_...
16  {'regressor__subsample': 0.8, 'regressor__reg_...
17  {'regressor__subsample': 0.6, 'regressor__reg_...
18  {'regressor__subsample': 0.7, 'regressor__reg_...
19  {'regressor__subsample': 0.6, 'regressor__reg_...
20  {'regressor__subsample': 0.9, 'regressor__reg_...
21  {'regressor__subsample': 0.6, 'regressor__reg_...
22  {'regressor__subsample': 1.0, 'regressor__reg_...
23  {'regressor__subsample': 0.8, 'regressor__reg_...
24  {'regressor__subsample': 0.6, 'regressor__reg_...
25  {'regressor__subsample': 0.9, 'regressor__reg_...
26  {'regressor__subsample': 1.0, 'regressor__reg_...
27  {'regressor__subsample': 0.6, 'regressor__reg_...
28  {'regressor__subsample': 0.6, 'regressor__reg_...
29  {'regressor__subsample': 0.8, 'regressor__reg_...
30  {'regressor__subsample': 0.6, 'regressor__reg_...
31  {'regressor__subsample': 0.8, 'regressor__reg_...
32  {'regressor__subsample': 0.8, 'regressor__reg_...
33  {'regressor__subsample': 0.8, 'regressor__reg_...
34  {'regressor__subsample': 0.7, 'regressor__reg_...
35  {'regressor__subsample': 0.7, 'regressor__reg_...
36  {'regressor__subsample': 0.7, 'regressor__reg_...
37  {'regressor__subsample': 0.7, 'regressor__reg_...
38  {'regressor__subsample': 0.8, 'regressor__reg_...
39  {'regressor__subsample': 0.6, 'regressor__reg_...

                                          fold_rmsles
0   [0.5872705601534111, 0.7035874242125278, 0.613...
1   [0.5951604519020816, 0.7205844695192983, 0.600...
2   [0.596503466849359, 0.7223355770424025, 0.5979...
3   [0.596699208927187, 0.720707043698135, 0.60585...
4   [0.5986519109312993, 0.722822224828737, 0.6023...
5   [0.5969141740426891, 0.7248144108139982, 0.606...
6   [0.601260551732781, 0.7233044182200875, 0.6068...
7   [0.5987995116710654, 0.7289033265572854, 0.604...
8   [0.6062568883646137, 0.7295345234352519, 0.603...
9   [0.6086620496325139, 0.72552788930992, 0.60603...
10  [0.6004977239779433, 0.7363003267695756, 0.606...
11  [0.6094611803676492, 0.7303247968412303, 0.604...
12  [0.6077629365377556, 0.7315986340160756, 0.611...
13  [0.6095074239185329, 0.737337781600884, 0.6153...
14  [0.6114209320058971, 0.7410112987900362, 0.610...
15  [0.6104658699025279, 0.7455155267642113, 0.607...
16  [0.6148314147997535, 0.7441183135122119, 0.605...
17  [0.6110813380045469, 0.7476130452234487, 0.606...
18  [0.6106224809879973, 0.7453781770517592, 0.609...
19  [0.6121415327280566, 0.7453722483836259, 0.608...
20  [0.6138526838984806, 0.7416735414627535, 0.611...
21  [0.6126997597076432, 0.7467118432290076, 0.610...
22  [0.6133147498748736, 0.747679532840456, 0.6086...
23  [0.6101917485350343, 0.7444588076277596, 0.620...
24  [0.6200403848614668, 0.7375662767643821, 0.620...
25  [0.616741823593187, 0.7471106247415087, 0.6152...
26  [0.6146208792078155, 0.7443889184453895, 0.621...
27  [0.6140105787225252, 0.7464612175616012, 0.623...
28  [0.6214751281857074, 0.7440495865453535, 0.621...
29  [0.6124139579511618, 0.7491084395555363, 0.625...
30  [0.6186425688314532, 0.7565798587700037, 0.612...
31  [0.6258994958463955, 0.7501129626693877, 0.612...
32  [0.6170065800844634, 0.7438539032859359, 0.628...
33  [0.6190799786983578, 0.7542815964318427, 0.618...
34  [0.6215665795363882, 0.746777990894011, 0.6285...
35  [0.62059593794636, 0.7578203979837331, 0.62073...
36  [0.6175508043480953, 0.762638197324062, 0.6213...
37  [0.6164798190660655, 0.7645962608132206, 0.623...
38  [0.6172346341025365, 0.7686984271306896, 0.623...
39  [0.6300589825645841, 0.7673635824380589, 0.626...  )

In [14]:
evaluate(X = x_train,y = y_train,model=model)

[ 7.16276425 12.65297505  8.88162355 ...  2.3719451   3.6434086
  1.00042298]
MAE:   4.771
RMSE:  6.504
RMSLE: 0.595

In [15]:
import joblib
# Save the model
joblib.dump(model, f'models/{model_name}v4.joblib')

['models/lightgbmv4.joblib']